# Meta analysis of Combined FIS with COGENT, also used for meta analysis
# of measured and imputed FIS

# === DECLARE SOME PARAMETERS ===
SCHEME STDERR
CUSTOMVARIABLE N
AVERAGEFREQ ON
MINWEIGHT 10000
TRACKPOSITIONS ON

# === DESCRIBE AND PROCESS INPUT 1 ===
CHROMOSOME CHR
POSITION BP
MARKER SNP
FREQLABEL EAF
ALLELE A1 A2
EFFECT BETA
PVALUE P
STDERR  SE
LABEL N AS N
PROCESS ./all.mean.iq2.ADD-INT_SNP.gwas.gz

# === DESCRIBE AND PROCESS INPUT 2 ===
CHROMOSOME CHR
POSITION POS
MARKER rsID
FREQLABEL EAF
ALLELE EFFECT_ALLELE OTHER_ALLELE
EFFECT BETA
PVALUE PVAL
STDERR SE
LABEL N AS N
PROCESS /home/dvandenberg/storage/sumstats/raw/intelligence/CLEANED.COGENT.withChrPos.txt.gz

# === FINALIZE ===
OUTFILE ./combined_FIS_cogent_meta .txt
ANALYZE
CLEAR
QUIT  