# === DECLARE SOME PARAMETERS ===
SCHEME STDERR
CUSTOMVARIABLE N
AVERAGEFREQ ON
MINWEIGHT 10000

# === DESCRIBE AND PROCESS INPUT ===
MARKER SNP
FREQLABEL AF1
ALLELE A1 A2
EFFECT BETA
PVALUE P
STDERR  SE
LABEL N AS N
PROCESS ./FI-GWAS/measured_FIS.fastGWA.gz
PROCESS ./FI-GWAS/imputed_FIS.fastGWA.gz

# === FINALIZE ===
OUTFILE ./FI-GWAS/combined_FIS_Meta .txt
ANALYZE
CLEAR
QUIT  